# Podstawy pakietu Numpy
Analiza podstawowych **struktur pakietu**, przykłady budowy <span style="color:red; font-size:16pt; font-family:Impact;">struktur danych</span>.
<p>
<img src="numpy.png">
</p>

In [6]:
import numpy as np

In [2]:
import numpy as np

def split_into_words(sentence):
    words = sentence.split()
    return words

# Test the function
test_sentence = "To jest przykładowe zdanie do podziału na słowa"
print(split_into_words(test_sentence))

['To', 'jest', 'przykładowe', 'zdanie', 'do', 'podziału', 'na', 'słowa']


In [3]:

def convert_num_to_str(num):
    """
    This function converts a number to a string.
    It accepts both integers and floats and returns them as a string.
    """
    return str(num)
    
# Test the function
test_number = 12345
print(convert_num_to_str(test_number))  # Expected output: "12345"

12345


In [4]:

def create_array(data_list, desired_shape):
    """
    This function converts a list into a numpy array of a desired shape.
    """
    if np.prod(desired_shape) == len(data_list):
        return np.array(data_list).reshape(desired_shape)
    else:
        return "Error: List length doesn't fit the desired shape"

# Test the function
test_list = [1, 2, 3, 4, 6, 7, 8, 9]
test_shape = (2, 4)
print(create_array(test_list, test_shape))

[[1 2 3 4]
 [6 7 8 9]]


In [7]:
np.zeros(8)

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
print(np.ones(11))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [9]:
np.empty(10)

array([4.64841424e-310, 0.00000000e+000, 8.48798317e-313, 2.37663529e-312,
 2.35541533e-312, 2.14321575e-312, 8.48798317e-313, 1.03977794e-312,
 8.70018274e-313, 6.95010660e-310])

In [10]:
u = np.arange(1,77,3)
u

array([ 1, 4, 7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49,
 52, 55, 58, 61, 64, 67, 70, 73, 76])

In [11]:
print(type(u))

<class 'numpy.ndarray'>


In [13]:
zlista = [5,3,5,26,25,8,37,7]
print(type(zlista))

<class 'list'>


In [14]:
k = np.linspace(0,10,num=5)
k

array([ 0. , 2.5, 5. , 7.5, 10. ])

In [15]:
mlista = np.array(zlista)
print(mlista)
print(type(mlista))

[ 5  3  5 26 25  8 37  7]
<class 'numpy.ndarray'>


In [17]:
kl = (4,223,67,89,24,1,5)
znum = np.array(kl)
print(znum)
print(type(znum))

[  4 223  67  89  24   1   5]
<class 'numpy.ndarray'>


In [19]:
mlista = list(znum)
print(mlista)
print(type(mlista))

[4, 223, 67, 89, 24, 1, 5]
<class 'list'>


In [20]:
zb = {45,25,8,9,12,45,7,25}
znp = np.array(zb)
print(znp)
print(type(znp))

{7, 8, 9, 12, 45, 25}
<class 'numpy.ndarray'>
