# Podstawy pakietu Numpy
Analiza podstawowych **struktur pakietu**, przykłady budowy <span style="color:red; font-size:16pt; font-family:Impact;">struktur danych</span>.
<p>
<img src="numpy.png">
</p>

In [1]:
import numpy as np

In [2]:
import numpy as np

def split_into_words(sentence):
    words = sentence.split()
    return words

# Test the function
test_sentence = "To jest przykładowe zdanie do podziału na słowa"
print(split_into_words(test_sentence))

['To', 'jest', 'przykładowe', 'zdanie', 'do', 'podziału', 'na', 'słowa']


In [3]:

def convert_num_to_str(num):
    """
    This function converts a number to a string.
    It accepts both integers and floats and returns them as a string.
    """
    return str(num)
    
# Test the function
test_number = 12345
print(convert_num_to_str(test_number))  # Expected output: "12345"

12345


In [4]:

def create_array(data_list, desired_shape):
    """
    This function converts a list into a numpy array of a desired shape.
    """
    if np.prod(desired_shape) == len(data_list):
        return np.array(data_list).reshape(desired_shape)
    else:
        return "Error: List length doesn't fit the desired shape"

# Test the function
test_list = [1, 2, 3, 4, 6, 7, 8, 9]
test_shape = (2, 4)
print(create_array(test_list, test_shape))

[[1 2 3 4]
 [6 7 8 9]]


In [5]:
np.zeros(8)

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
print(np.ones(11))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [7]:
np.empty(10)

array([6.93118168e-310, 4.68127670e-310, 4.68127663e-310, 0.00000000e+000,
 0.00000000e+000, 0.00000000e+000, 4.94065646e-324, 1.39064994e-309,
 0.00000000e+000, 0.00000000e+000])

In [8]:
u = np.arange(1,77,3)
u

array([ 1, 4, 7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49,
 52, 55, 58, 61, 64, 67, 70, 73, 76])

In [9]:
print(type(u))

<class 'numpy.ndarray'>


In [10]:
zlista = [5,3,5,26,25,8,37,7]
print(type(zlista))

<class 'list'>


In [11]:
k = np.linspace(0,10,num=5)
k

array([ 0. , 2.5, 5. , 7.5, 10. ])

In [12]:
mlista = np.array(zlista)
print(mlista)
print(type(mlista))

[ 5  3  5 26 25  8 37  7]
<class 'numpy.ndarray'>


In [13]:
kl = (4,223,67,89,24,1,5)
znum = np.array(kl)
print(znum)
print(type(znum))

[  4 223  67  89  24   1   5]
<class 'numpy.ndarray'>


In [14]:
mlista = list(znum)
print(mlista)
print(type(mlista))

[4, 223, 67, 89, 24, 1, 5]
<class 'list'>


In [15]:
zb = {45,25,8,9,12,45,7,25}
znp = np.array(zb)
print(znp)
print(type(znp))

{7, 8, 9, 12, 45, 25}
<class 'numpy.ndarray'>


In [16]:
mlista.sort()
mlista

[1, 4, 5, 24, 67, 89, 223]

In [20]:
l1 = [2,5,63,6,56]
l2 = [35,63,2,7,3]
l3 = [4,2,6,79,5]

l = l1+l2+l3
l

[2, 5, 63, 6, 56, 35, 63, 2, 7, 3, 4, 2, 6, 79, 5]

In [21]:
a = np.array(l1)
b = np.array(l2)
c = np.array(l3)

In [22]:
f = a+b+c
f

array([41, 70, 71, 92, 64])

In [25]:
ca = np.concatenate((a,b,c))
ca

array([ 2, 5, 63, 6, 56, 35, 63, 2, 7, 3, 4, 2, 6, 79, 5])

In [26]:
z1 = [[56,4],[43,5]]
z1

[[56, 4], [43, 5]]

In [28]:
z1[0][1]

4

In [30]:
a1 = np.array(z1)
a1

array([[56, 4],
 [43, 5]])

In [31]:
a1[0,1]

4

In [32]:
a1[0][1]

4

In [33]:
mm = np.array([[24,63,6],[64,25,6]])
mm

array([[24, 63, 6],
 [64, 25, 6]])

In [34]:
x = np.array([[4,2,6],[7,5,2],[8,3,2]])
y = np.array([[9,9,4],[2,1,3],[1,1,5]])

In [35]:
x

array([[4, 2, 6],
 [7, 5, 2],
 [8, 3, 2]])

In [36]:
y

array([[9, 9, 4],
 [2, 1, 3],
 [1, 1, 5]])

In [38]:
p = np.concatenate((x,y),axis=1)
p

array([[4, 2, 6, 9, 9, 4],
 [7, 5, 2, 2, 1, 3],
 [8, 3, 2, 1, 1, 5]])

In [39]:
q = np.concatenate((x,y),axis=0)
q

array([[4, 2, 6],
 [7, 5, 2],
 [8, 3, 2],
 [9, 9, 4],
 [2, 1, 3],
 [1, 1, 5]])

In [40]:
prosta = np.arange(12)
prosta

array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11])

In [46]:
fp = prosta.reshape(3,4)
fp

array([[ 0, 1, 2, 3],
 [ 4, 5, 6, 7],
 [ 8, 9, 10, 11]])

In [47]:
mac1 = np.array([[2,3],[4,5],[9,9]])
mac1

array([[2, 3],
 [4, 5],
 [9, 9]])

In [48]:
mac1.shape

(3, 2)

In [49]:
w1 = mac1.reshape(6)
w1

array([2, 3, 4, 5, 9, 9])

In [50]:
ar = np.array([1,7,3,89,32,5,89,0,7,12,4,6,23])
ar.shape

(13,)

In [51]:
ar[:7].shape

(7,)

In [52]:
ar[2:5].shape

(3,)

In [53]:
w = np.array([[1,2,3,4],[9,10,11,12],[23,78,43,65]])
w

array([[ 1, 2, 3, 4],
 [ 9, 10, 11, 12],
 [23, 78, 43, 65]])

In [54]:
w[w<5]

array([1, 2, 3, 4])

In [55]:
pc = (w>=5)
w[pc]

array([ 9, 10, 11, 12, 23, 78, 43, 65])

In [56]:
w[w%2==0]

array([ 2, 4, 10, 12, 78])

In [58]:
cv = (w>2)&(w<=21)
w[cv]

array([ 3, 4, 9, 10, 11, 12])

In [59]:
sv = (w<8)|(w>=33)
w[sv]

array([ 1, 2, 3, 4, 78, 43, 65])

In [60]:
#operacje  na wektorach
dane = np.array([1,3,8])
one = np.ones(3,dtype=int)
tw = np.array([2,2,3])

In [61]:
print(dane+one)

[2 4 9]


In [62]:
print(dane-one)

[0 2 7]


In [63]:
print(dane*tw)

[ 2  6 24]


In [64]:
print(dane/tw)

[0.5        1.5        2.66666667]


In [65]:
print(dane*1.88)

[ 1.88  5.64 15.04]


In [67]:
on = np.ones(5,dtype=int)
on

array([1, 1, 1, 1, 1])

In [68]:
m1 = np.array([[443,545,2],[75,36,887],[1,2,1]])
m2 = np.array([[24,54,235],[5,35,2],[1,6,9]])
wynik = (m1+m2)*m1
print(wynik)

[[206881 326455    474]
 [  6000   2556 788543]
 [     2     16     10]]


In [69]:
print(f'wartość najmniejsza: {wynik.min()}')
print(f'wartość największa: {wynik.max()}')
print(f'wartość średnia: {wynik.mean()}')
print(f'wartość odchylenia standardowego: {wynik.std()}')

wartość najmniejsza: 2
wartość największa: 788543
wartość średnia: 147881.88888888888
wartość odchylenia standardowego: 252629.2757414594
