In [1]:
import tensorflow as tf

In [2]:
print(f'wersja tf: {tf.__version__}')

wersja tf: 2.10.1


In [3]:
mnist = tf.keras.datasets.mnist
(x_train,y_train),(x_test,y_test) = mnist.load_data()
x_train, x_test = x_train/255.0, x_test/255.0

11490434/11490434 [==============================] - 1s 0us/step


In [4]:
x_train.shape

(60000, 28, 28)

In [5]:
x_test.shape

(10000, 28, 28)

In [9]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28,28)),
    tf.keras.layers.Dense(128,activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

In [10]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.6939567 , 0.39777344, -0.2478203 , -0.0985157 , 0.03442194,
 -0.56218964, -0.04755493, 0.11193204, -0.26007655, 0.48011225]],
 dtype=float32)

In [11]:
tf.nn.softmax(predictions).numpy

<bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(1, 10), dtype=float32, numpy=
array([[0.05129839, 0.15283968, 0.08014166, 0.09304659, 0.10627584,
        0.05852338, 0.09791122, 0.11484095, 0.07916541, 0.16595693]],
      dtype=float32)>>

In [12]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [13]:
loss_fn(y_train[:1],predictions).numpy()

2.8383288

In [14]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy']
              )

In [15]:
model.fit(x_train,y_train,epochs=5)

Epoch 1/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.3008 - accuracy: 0.9129
Epoch 2/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1457 - accuracy: 0.9568
Epoch 3/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1106 - accuracy: 0.9665
Epoch 4/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0900 - accuracy: 0.9724
Epoch 5/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0761 - accuracy: 0.9764


In [21]:
model.evaluate(x_test,y_test,verbose=2)

[0.0720495656132698, 0.9787999987602234]

In [22]:
probability_model = tf.keras.Sequential([
    model,
    tf.keras.layers.Softmax()
])

In [23]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[5.02694153e-09, 2.99116198e-09, 4.09676477e-06, 2.98652623e-04,
        1.68692199e-10, 3.73064665e-07, 1.17939165e-11, 9.99683022e-01,
        8.53058964e-07, 1.30585004e-05],
       [8.75770151e-11, 5.36222942e-05, 9.99944687e-01, 1.66158088e-06,
        1.09823687e-15, 6.35286099e-08, 1.38139600e-09, 2.09441969e-12,
        3.42696787e-08, 1.68316526e-14],
       [1.39133567e-08, 9.99324441e-01, 6.74352923e-05, 3.21080370e-06,
        1.39865888e-05, 8.32615751e-06, 3.62100263e-06, 4.17386851e-04,
        1.60961383e-04, 6.33254274e-07],
       [9.99738634e-01, 3.69647069e-08, 5.25858413e-05, 1.62545246e-06,
        2.57005431e-05, 1.85245826e-05, 3.62519422e-05, 1.21706173e-04,
        4.41793802e-09, 4.91671972e-06],
       [7.04857470e-08, 4.12764961e-10, 7.98612518e-07, 5.17142240e-09,
        9.98976350e-01, 5.45167666e-07, 1.39110639e-07, 1.13419765e-05,
        1.26219021e-07, 1.01056544e-03]], dtype=float32)>