In [1]:
import tensorflow as tf

In [2]:
print(f'wersja tf: {tf.__version__}')

wersja tf: 2.10.1


In [3]:
mnist = tf.keras.datasets.mnist
(x_train,y_train),(x_test,y_test) = mnist.load_data()
x_train, x_test = x_train/255.0, x_test/255.0

11490434/11490434 [==============================] - 1s 0us/step


In [4]:
x_train.shape

(60000, 28, 28)

In [5]:
x_test.shape

(10000, 28, 28)

In [9]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28,28)),
    tf.keras.layers.Dense(128,activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

In [10]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.6939567 , 0.39777344, -0.2478203 , -0.0985157 , 0.03442194,
 -0.56218964, -0.04755493, 0.11193204, -0.26007655, 0.48011225]],
 dtype=float32)

In [11]:
tf.nn.softmax(predictions).numpy

<bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(1, 10), dtype=float32, numpy=
array([[0.05129839, 0.15283968, 0.08014166, 0.09304659, 0.10627584,
        0.05852338, 0.09791122, 0.11484095, 0.07916541, 0.16595693]],
      dtype=float32)>>

In [12]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [13]:
loss_fn(y_train[:1],predictions).numpy()

2.8383288

In [14]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy']
              )