In [1]:
import pandas as pd

In [2]:
obj = pd.Series([4,6,8,-3,4])
obj

0 4
1 6
2 8
3 -3
4 4
dtype: int64

In [3]:
obj.values

array([ 4, 6, 8, -3, 4])

In [4]:
obj.index

RangeIndex(start=0, stop=5, step=1)

In [5]:
obj2 = pd.Series([7,3,6,2,6],index=['a','b','c','k','p'])
obj2

a 7
b 3
c 6
k 2
p 6
dtype: int64

In [6]:
obj2["k"]

2

In [7]:
obj2["p"]=555
obj2

a 7
b 3
c 6
k 2
p 555
dtype: int64

In [8]:
obj2[["c","p","a"]]

c 6
p 555
a 7
dtype: int64

In [9]:
obj2[obj2>6]

a 7
p 555
dtype: int64

In [10]:
obj2*3

a 21
b 9
c 18
k 6
p 1665
dtype: int64

In [11]:
'b' in obj2

True

In [12]:
'z' in obj2

False

In [13]:
sdata = {'Warszawa':6453,'Kraków':7543,'Lublin':5435,'Gdańsk':6488}
sdata

{'Warszawa': 6453, 'Kraków': 7543, 'Lublin': 5435, 'Gdańsk': 6488}

In [15]:
obj3 = pd.Series(sdata,name="liczba wniosków")
obj3

Warszawa 6453
Kraków 7543
Lublin 5435
Gdańsk 6488
Name: liczba wniosków, dtype: int64

In [16]:
miasta = ['Poznań','Kraków','Katowice','Lublin']
obj4 = pd.Series(sdata,index=miasta)
obj4

Poznań NaN
Kraków 7543.0
Katowice NaN
Lublin 5435.0
dtype: float64

In [17]:
pd.isnull(obj4)

Poznań True
Kraków False
Katowice True
Lublin False
dtype: bool

In [18]:
obj3+obj4

Gdańsk NaN
Katowice NaN
Kraków 15086.0
Lublin 10870.0
Poznań NaN
Warszawa NaN
dtype: float64

In [19]:
#obiekt DataFrame
fdata = {'miasto':['Warszawa','Warszawa','Warszawa','Kraków','Kraków','Kraków'],
         'rok':[2017,2018,2019,2019,2020,2021],
         'populacja':[2.5,2.7,2.75,0.8,0.85,0.92]}
frame = pd.DataFrame(fdata)

In [20]:
frame

miasto 
 rok 
 populacja 
 
 
 
 
 0 
 Warszawa 
 2017 
 2.50 
 
 
 1 
 Warszawa 
 2018 
 2.70 
 
 
 2 
 Warszawa 
 2019 
 2.75 
 
 
 3 
 Kraków 
 2019 
 0.80 
 
 
 4 
 Kraków 
 2020 
 0.85 
 
 
 5 
 Kraków 
 2021 
 0.92

In [22]:
frame2 = pd.DataFrame(fdata,columns=['rok','miasto','populacja','waga'],index=['jeden','drugi','trzeci','czwarty','piąty','szósty'])

In [23]:
frame2

rok 
 miasto 
 populacja 
 waga 
 
 
 
 
 jeden 
 2017 
 Warszawa 
 2.50 
 NaN 
 
 
 drugi 
 2018 
 Warszawa 
 2.70 
 NaN 
 
 
 trzeci 
 2019 
 Warszawa 
 2.75 
 NaN 
 
 
 czwarty 
 2019 
 Kraków 
 0.80 
 NaN 
 
 
 piąty 
 2020 
 Kraków 
 0.85 
 NaN 
 
 
 szósty 
 2021 
 Kraków 
 0.92 
 NaN

In [24]:
frame2['waga'] = 19.99
frame2

rok 
 miasto 
 populacja 
 waga 
 
 
 
 
 jeden 
 2017 
 Warszawa 
 2.50 
 19.99 
 
 
 drugi 
 2018 
 Warszawa 
 2.70 
 19.99 
 
 
 trzeci 
 2019 
 Warszawa 
 2.75 
 19.99 
 
 
 czwarty 
 2019 
 Kraków 
 0.80 
 19.99 
 
 
 piąty 
 2020 
 Kraków 
 0.85 
 19.99 
 
 
 szósty 
 2021 
 Kraków 
 0.92 
 19.99

In [25]:
import numpy as np

In [26]:
frame2['waga'] = np.arange(6.)
frame2

rok 
 miasto 
 populacja 
 waga 
 
 
 
 
 jeden 
 2017 
 Warszawa 
 2.50 
 0.0 
 
 
 drugi 
 2018 
 Warszawa 
 2.70 
 1.0 
 
 
 trzeci 
 2019 
 Warszawa 
 2.75 
 2.0 
 
 
 czwarty 
 2019 
 Kraków 
 0.80 
 3.0 
 
 
 piąty 
 2020 
 Kraków 
 0.85 
 4.0 
 
 
 szósty 
 2021 
 Kraków 
 0.92 
 5.0

In [27]:
frame2['waga'] = np.array([15,17,8.8,9.2,-4,5])
frame2

rok 
 miasto 
 populacja 
 waga 
 
 
 
 
 jeden 
 2017 
 Warszawa 
 2.50 
 15.0 
 
 
 drugi 
 2018 
 Warszawa 
 2.70 
 17.0 
 
 
 trzeci 
 2019 
 Warszawa 
 2.75 
 8.8 
 
 
 czwarty 
 2019 
 Kraków 
 0.80 
 9.2 
 
 
 piąty 
 2020 
 Kraków 
 0.85 
 -4.0 
 
 
 szósty 
 2021 
 Kraków 
 0.92 
 5.0

In [32]:
frame2.to_csv("miasta.csv",encoding='utf-8')

In [41]:
daty = pd.date_range("20240324",periods=6,freq='w-mon')
daty

DatetimeIndex(['2024-03-25', '2024-04-01', '2024-04-08', '2024-04-15',
               '2024-04-22', '2024-04-29'],
              dtype='datetime64[ns]', freq='W-MON')

In [58]:
fr = pd.DataFrame(np.random.randn(6,4),index=daty,columns=list("ABCD"))
fr

A 
 B 
 C 
 D 
 
 
 
 
 2024-03-25 
 0.909875 
 1.120715 
 -1.654977 
 1.197706 
 
 
 2024-04-01 
 -0.960386 
 0.659500 
 -0.943581 
 0.466567 
 
 
 2024-04-08 
 -0.665721 
 1.834840 
 -0.505080 
 1.178706 
 
 
 2024-04-15 
 -0.828866 
 -0.732300 
 0.011787 
 -0.178446 
 
 
 2024-04-22 
 -0.649875 
 0.850254 
 -0.462466 
 0.762323 
 
 
 2024-04-29 
 0.258061 
 1.433901 
 0.440013 
 0.525898

In [47]:
s = 'lajkonik'
s

'lajkonik'

In [48]:
s[2:5]

'jko'

In [49]:
s[::-1]

'kinokjal'

In [59]:
nf = fr.to_numpy()
nf

array([[ 0.90987486, 1.12071482, -1.65497749, 1.19770604],
 [-0.96038604, 0.65950006, -0.9435805 , 0.46656696],
 [-0.66572052, 1.83484039, -0.50508047, 1.17870627],
 [-0.82886565, -0.73229982, 0.01178659, -0.17844598],
 [-0.64987541, 0.85025365, -0.4624664 , 0.76232328],
 [ 0.2580613 , 1.43390065, 0.44001265, 0.5258975 ]])

In [60]:
print(type(fr))
print(type(nf))

<class 'pandas.core.frame.DataFrame'>
<class 'numpy.ndarray'>


In [61]:
newframe = pd.DataFrame(nf)
newframe

0 
 1 
 2 
 3 
 
 
 
 
 0 
 0.909875 
 1.120715 
 -1.654977 
 1.197706 
 
 
 1 
 -0.960386 
 0.659500 
 -0.943581 
 0.466567 
 
 
 2 
 -0.665721 
 1.834840 
 -0.505080 
 1.178706 
 
 
 3 
 -0.828866 
 -0.732300 
 0.011787 
 -0.178446 
 
 
 4 
 -0.649875 
 0.850254 
 -0.462466 
 0.762323 
 
 
 5 
 0.258061 
 1.433901 
 0.440013 
 0.525898

In [62]:
fr.head(2)

A 
 B 
 C 
 D 
 
 
 
 
 2024-03-25 
 0.909875 
 1.120715 
 -1.654977 
 1.197706 
 
 
 2024-04-01 
 -0.960386 
 0.659500 
 -0.943581 
 0.466567

In [63]:
fr.tail(3)

A 
 B 
 C 
 D 
 
 
 
 
 2024-04-15 
 -0.828866 
 -0.732300 
 0.011787 
 -0.178446 
 
 
 2024-04-22 
 -0.649875 
 0.850254 
 -0.462466 
 0.762323 
 
 
 2024-04-29 
 0.258061 
 1.433901 
 0.440013 
 0.525898

In [64]:
fr.describe()

A 
 B 
 C 
 D 
 
 
 
 
 count 
 6.000000 
 6.000000 
 6.000000 
 6.000000 
 
 
 mean 
 -0.322819 
 0.861152 
 -0.519051 
 0.658792 
 
 
 std 
 0.740821 
 0.885816 
 0.731511 
 0.515177 
 
 
 min 
 -0.960386 
 -0.732300 
 -1.654977 
 -0.178446 
 
 
 25% 
 -0.788079 
 0.707188 
 -0.833955 
 0.481400 
 
 
 50% 
 -0.657798 
 0.985484 
 -0.483773 
 0.644110 
 
 
 75% 
 0.031077 
 1.355604 
 -0.106777 
 1.074611 
 
 
 max 
 0.909875 
 1.834840 
 0.440013 
 1.197706

In [65]:
fr.T

2024-03-25 
 2024-04-01 
 2024-04-08 
 2024-04-15 
 2024-04-22 
 2024-04-29 
 
 
 
 
 A 
 0.909875 
 -0.960386 
 -0.665721 
 -0.828866 
 -0.649875 
 0.258061 
 
 
 B 
 1.120715 
 0.659500 
 1.834840 
 -0.732300 
 0.850254 
 1.433901 
 
 
 C 
 -1.654977 
 -0.943581 
 -0.505080 
 0.011787 
 -0.462466 
 0.440013 
 
 
 D 
 1.197706 
 0.466567 
 1.178706 
 -0.178446 
 0.762323 
 0.525898

In [67]:
fr.sort_index(axis=1,ascending=False)

D 
 C 
 B 
 A 
 
 
 
 
 2024-03-25 
 1.197706 
 -1.654977 
 1.120715 
 0.909875 
 
 
 2024-04-01 
 0.466567 
 -0.943581 
 0.659500 
 -0.960386 
 
 
 2024-04-08 
 1.178706 
 -0.505080 
 1.834840 
 -0.665721 
 
 
 2024-04-15 
 -0.178446 
 0.011787 
 -0.732300 
 -0.828866 
 
 
 2024-04-22 
 0.762323 
 -0.462466 
 0.850254 
 -0.649875 
 
 
 2024-04-29 
 0.525898 
 0.440013 
 1.433901 
 0.258061

In [69]:
fr.sort_values(by="B",ascending=True)

A 
 B 
 C 
 D 
 
 
 
 
 2024-04-15 
 -0.828866 
 -0.732300 
 0.011787 
 -0.178446 
 
 
 2024-04-01 
 -0.960386 
 0.659500 
 -0.943581 
 0.466567 
 
 
 2024-04-22 
 -0.649875 
 0.850254 
 -0.462466 
 0.762323 
 
 
 2024-03-25 
 0.909875 
 1.120715 
 -1.654977 
 1.197706 
 
 
 2024-04-29 
 0.258061 
 1.433901 
 0.440013 
 0.525898 
 
 
 2024-04-08 
 -0.665721 
 1.834840 
 -0.505080 
 1.178706

In [70]:
obj5 = pd.Series([4.5,7.2,-5.6,5],index=['d','a','k','h'])
obj5

d 4.5
a 7.2
k -5.6
h 5.0
dtype: float64

In [71]:
obj6 = obj5.reindex(['d','k','a','h','q'])
obj6

d 4.5
k -5.6
a 7.2
h 5.0
q NaN
dtype: float64

In [72]:
obj7 = pd.Series(['blue','yellow','purple','white'],index=[0,2,5,8])
obj7

0 blue
2 yellow
5 purple
8 white
dtype: object

In [74]:
obj7.reindex(range(10),method='ffill')

0 blue
1 blue
2 yellow
3 yellow
4 yellow
5 purple
6 purple
7 purple
8 white
9 white
dtype: object

In [75]:
data = pd.DataFrame(np.arange(16).reshape(4,4),
                    index=['Kraków','Warszawa','Lublin','Katowice'],
                    columns=['cecha_1','cecha_2','cecha_3','cecha_4'])

data

cecha_1 
 cecha_2 
 cecha_3 
 cecha_4 
 
 
 
 
 Kraków 
 0 
 1 
 2 
 3 
 
 
 Warszawa 
 4 
 5 
 6 
 7 
 
 
 Lublin 
 8 
 9 
 10 
 11 
 
 
 Katowice 
 12 
 13 
 14 
 15

In [76]:
data['cecha_2']

Kraków 1
Warszawa 5
Lublin 9
Katowice 13
Name: cecha_2, dtype: int64

In [78]:
data.loc['Kraków',['cecha_1','cecha_3']]

cecha_1 0
cecha_3 2
Name: Kraków, dtype: int64

In [81]:
data.iloc[2,[3,0,1]]

cecha_4 11
cecha_1 8
cecha_2 9
Name: Lublin, dtype: int64

In [80]:
data.iloc[[2,1],[3,0,1]]

cecha_4 
 cecha_1 
 cecha_2 
 
 
 
 
 Lublin 
 11 
 8 
 9 
 
 
 Warszawa 
 7 
 4 
 5

In [83]:
data.loc[:'Lublin',"cecha_4"]

Kraków 3
Warszawa 7
Lublin 11
Name: cecha_4, dtype: int64

In [84]:
data.iloc[1:3,:3]

cecha_1 
 cecha_2 
 cecha_3 
 
 
 
 
 Warszawa 
 4 
 5 
 6 
 
 
 Lublin 
 8 
 9 
 10

In [87]:
data.iloc[1:3,:3][data.cecha_3>9]

<ipython-input-87-75928d460596>:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  data.iloc[1:3,:3][data.cecha_3>9]


cecha_1 
 cecha_2 
 cecha_3 
 
 
 
 
 Lublin 
 8 
 9 
 10

In [88]:
df1 = pd.DataFrame(np.arange(9.).reshape((3,3)),columns=list('bcd'),index=['Kraków','Gdańsk','Toruń'])
df1

b 
 c 
 d 
 
 
 
 
 Kraków 
 0.0 
 1.0 
 2.0 
 
 
 Gdańsk 
 3.0 
 4.0 
 5.0 
 
 
 Toruń 
 6.0 
 7.0 
 8.0

In [89]:
df2 = pd.DataFrame(np.arange(12.).reshape((4,3)),columns=list('bde'),index=['Lublin','Kraków','Gdańsk','Rzeszów'])
df2

b 
 d 
 e 
 
 
 
 
 Lublin 
 0.0 
 1.0 
 2.0 
 
 
 Kraków 
 3.0 
 4.0 
 5.0 
 
 
 Gdańsk 
 6.0 
 7.0 
 8.0 
 
 
 Rzeszów 
 9.0 
 10.0 
 11.0

In [90]:
df1+df2

b 
 c 
 d 
 e 
 
 
 
 
 Gdańsk 
 9.0 
 NaN 
 12.0 
 NaN 
 
 
 Kraków 
 3.0 
 NaN 
 6.0 
 NaN 
 
 
 Lublin 
 NaN 
 NaN 
 NaN 
 NaN 
 
 
 Rzeszów 
 NaN 
 NaN 
 NaN 
 NaN 
 
 
 Toruń 
 NaN 
 NaN 
 NaN 
 NaN

In [91]:
df1-df2

b 
 c 
 d 
 e 
 
 
 
 
 Gdańsk 
 -3.0 
 NaN 
 -2.0 
 NaN 
 
 
 Kraków 
 -3.0 
 NaN 
 -2.0 
 NaN 
 
 
 Lublin 
 NaN 
 NaN 
 NaN 
 NaN 
 
 
 Rzeszów 
 NaN 
 NaN 
 NaN 
 NaN 
 
 
 Toruń 
 NaN 
 NaN 
 NaN 
 NaN

In [92]:
arr = np.arange(12.).reshape((3,4))
arr

array([[ 0., 1., 2., 3.],
 [ 4., 5., 6., 7.],
 [ 8., 9., 10., 11.]])

In [93]:
arr[0]

array([0., 1., 2., 3.])

In [95]:
arr-arr[0]*2

array([[ 0., -1., -2., -3.],
 [ 4., 3., 2., 1.],
 [ 8., 7., 6., 5.]])

In [96]:
fm = pd.DataFrame(np.arange(12.).reshape((4,3)),
                  columns=list('bde'),
                  index=['Lublin','Kraków','Gdańsk','Wrocław'])
series = fm.iloc[0]
fm

b 
 d 
 e 
 
 
 
 
 Lublin 
 0.0 
 1.0 
 2.0 
 
 
 Kraków 
 3.0 
 4.0 
 5.0 
 
 
 Gdańsk 
 6.0 
 7.0 
 8.0 
 
 
 Wrocław 
 9.0 
 10.0 
 11.0

In [97]:
series

b 0.0
d 1.0
e 2.0
Name: Lublin, dtype: float64

In [99]:
print(type(fm))
print(type(series))

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>


In [116]:
fm - series

b 
 d 
 e 
 
 
 
 
 Lublin 
 0.0 
 0.0 
 0.0 
 
 
 Kraków 
 3.0 
 3.0 
 3.0 
 
 
 Gdańsk 
 6.0 
 6.0 
 6.0 
 
 
 Wrocław 
 9.0 
 9.0 
 9.0

In [121]:
sz = {'b':4,'d':12,'e':35}
ss = pd.Series(sz,name="Kraków")
ss

b 4
d 12
e 35
Name: Kraków, dtype: int64

In [123]:
wynik =fm*ss
wynik

b 
 d 
 e 
 
 
 
 
 Lublin 
 0.0 
 12.0 
 70.0 
 
 
 Kraków 
 12.0 
 48.0 
 175.0 
 
 
 Gdańsk 
 24.0 
 84.0 
 280.0 
 
 
 Wrocław 
 36.0 
 120.0 
 385.0

In [125]:
wynik["e"]

Lublin 70.0
Kraków 175.0
Gdańsk 280.0
Wrocław 385.0
Name: e, dtype: float64

In [128]:
wynik = wynik.T

In [129]:
wynik["Lublin"]

b 0.0
d 12.0
e 70.0
Name: Lublin, dtype: float64

In [130]:
frame = pd.DataFrame(np.random.randn(4,3),columns=list('xyz'),
                     index=['Rzym','Londyn','Wiedeń','Paryż'])

In [131]:
frame

x 
 y 
 z 
 
 
 
 
 Rzym 
 0.261418 
 1.127462 
 -0.570872 
 
 
 Londyn 
 0.131120 
 0.197856 
 -2.330742 
 
 
 Wiedeń 
 0.342451 
 -0.175057 
 -0.863587 
 
 
 Paryż 
 -0.204460 
 0.106606 
 0.331108

In [132]:
np.abs(frame)

x 
 y 
 z 
 
 
 
 
 Rzym 
 0.261418 
 1.127462 
 0.570872 
 
 
 Londyn 
 0.131120 
 0.197856 
 2.330742 
 
 
 Wiedeń 
 0.342451 
 0.175057 
 0.863587 
 
 
 Paryż 
 0.204460 
 0.106606 
 0.331108

In [133]:
f = lambda x:x.max()-x.min()
frame.apply(f)

x 0.546910
y 1.302519
z 2.661851
dtype: float64

In [134]:
frame.apply(f,axis="columns")

Rzym 1.698334
Londyn 2.528598
Wiedeń 1.206038
Paryż 0.535568
dtype: float64

In [136]:
def f(x):
    return pd.Series([x.min(),x.max()],index=['min','max'])

spec = frame.apply(f,axis="columns")
spec

min 
 max 
 
 
 
 
 Rzym 
 -0.570872 
 1.127462 
 
 
 Londyn 
 -2.330742 
 0.197856 
 
 
 Wiedeń 
 -0.863587 
 0.342451 
 
 
 Paryż 
 -0.204460 
 0.331108

In [138]:
format = lambda x:'%.3f'% x
spec.applymap(format)

min 
 max 
 
 
 
 
 Rzym 
 -0.571 
 1.127 
 
 
 Londyn 
 -2.331 
 0.198 
 
 
 Wiedeń 
 -0.864 
 0.342 
 
 
 Paryż 
 -0.204 
 0.331

In [139]:
frame['y'].map(format)

Rzym 1.127
Londyn 0.198
Wiedeń -0.175
Paryż 0.107
Name: y, dtype: object